name: CI testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macOS-10.15 ]
        python-version: [ 3.8 ]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 35

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          sudo apt install -q -y tree
          tree -h -L 2
          cat OFA/requirements.txt
        if: runner.os == 'Linux'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install OFA
        working-directory: OFA
        run: pip install -r requirements.txt

      - name: Install dependencies
        run: |
          pip --version
          pip install -r requirements.txt -r tests/requirements.txt -U -q \
            -f https://download.pytorch.org/whl/cpu/torch_stable.html
          pip list

      - name: Tests
        run: python -m pytest tests -v
